services:
  server:
    stop_grace_period: 30s
    build:
      target: development
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "4m"
        max-file: "5"
    volumes:
      - "./resources:/app/resources"
    restart: unless-stopped
