services:
  server:
    build:
      target: production
      context: .
    logging:
      driver: "json-file"
      options:
        max-size: "4m"
        max-file: "5"
    restart: unless-stopped
